FROM node:20-bookworm

WORKDIR /app

# Install dependencies first (better cache)
COPY package.json package-lock.json yarn.lock ./
RUN npm install

# Copy the rest of the source
COPY . .

# Expo Web / Metro
EXPOSE 8081

CMD ["npm", "run", "web"]
