// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: club.sql

package repository

import (
	"context"
)

const createClub = `-- name: CreateClub :exec
INSERT INTO club (name, description, owner_user_id, banner_image, is_public)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type CreateClubParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	OwnerUserID string  `json:"owner_user_id"`
	BannerImage *string `json:"banner_image"`
	IsPublic    bool    `json:"is_public"`
}

func (q *Queries) CreateClub(ctx context.Context, arg CreateClubParams) error {
	_, err := q.db.ExecContext(ctx, createClub,
		arg.Name,
		arg.Description,
		arg.OwnerUserID,
		arg.BannerImage,
		arg.IsPublic,
	)
	return err
}

const createClubMembership = `-- name: CreateClubMembership :exec
INSERT INTO club_membership (user_id, club_id, user_points, user_streak, is_moderator)
VALUES (?1, ?2, 0, 0, false)
`

type CreateClubMembershipParams struct {
	UserID string `json:"user_id"`
	ClubID string `json:"club_id"`
}

func (q *Queries) CreateClubMembership(ctx context.Context, arg CreateClubMembershipParams) error {
	_, err := q.db.ExecContext(ctx, createClubMembership, arg.UserID, arg.ClubID)
	return err
}

const createClubPost = `-- name: CreateClubPost :exec
INSERT INTO club_post (club_id, user_id, content)
VALUES (?1, ?2, ?3)
`

type CreateClubPostParams struct {
	ClubID  string `json:"club_id"`
	UserID  string `json:"user_id"`
	Content string `json:"content"`
}

func (q *Queries) CreateClubPost(ctx context.Context, arg CreateClubPostParams) error {
	_, err := q.db.ExecContext(ctx, createClubPost, arg.ClubID, arg.UserID, arg.Content)
	return err
}

const createClubPostAttachment = `-- name: CreateClubPostAttachment :exec
INSERT INTO club_post_attachment (post_id, url)
VALUES (?1, ?2)
`

type CreateClubPostAttachmentParams struct {
	PostID string `json:"post_id"`
	Url    string `json:"url"`
}

func (q *Queries) CreateClubPostAttachment(ctx context.Context, arg CreateClubPostAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, createClubPostAttachment, arg.PostID, arg.Url)
	return err
}

const deleteClub = `-- name: DeleteClub :exec
DELETE FROM club
WHERE
    id = ?1
`

func (q *Queries) DeleteClub(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteClub, id)
	return err
}

const deleteClubMembership = `-- name: DeleteClubMembership :exec
DELETE FROM club_membership
WHERE
    user_id = ?1 AND club_id = ?2
`

type DeleteClubMembershipParams struct {
	UserID string `json:"user_id"`
	ClubID string `json:"club_id"`
}

func (q *Queries) DeleteClubMembership(ctx context.Context, arg DeleteClubMembershipParams) error {
	_, err := q.db.ExecContext(ctx, deleteClubMembership, arg.UserID, arg.ClubID)
	return err
}

const deleteClubPost = `-- name: DeleteClubPost :exec
DELETE FROM club_post
WHERE
    id = ?1
`

func (q *Queries) DeleteClubPost(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteClubPost, id)
	return err
}

const deleteClubPostAttachment = `-- name: DeleteClubPostAttachment :exec
DELETE FROM club_post_attachment
WHERE
    id = ?1
`

func (q *Queries) DeleteClubPostAttachment(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteClubPostAttachment, id)
	return err
}

const getClubLeaderboard = `-- name: GetClubLeaderboard :many
SELECT
    u.id, u.username, u.profile_picture,
    cm.user_points, cm.user_streak
FROM
    club_membership cm
    JOIN user u ON cm.user_id = u.id
WHERE
    club_id = ?1
ORDER BY cm.user_points DESC, cm.user_streak DESC
`

type GetClubLeaderboardRow struct {
	ID             string  `json:"id"`
	Username       string  `json:"username"`
	ProfilePicture *string `json:"profile_picture"`
	UserPoints     float64 `json:"user_points"`
	UserStreak     int64   `json:"user_streak"`
}

func (q *Queries) GetClubLeaderboard(ctx context.Context, clubID string) ([]GetClubLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, getClubLeaderboard, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClubLeaderboardRow
	for rows.Next() {
		var i GetClubLeaderboardRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.ProfilePicture,
			&i.UserPoints,
			&i.UserStreak,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClub = `-- name: UpdateClub :exec
UPDATE club
SET
    name = COALESCE(?1, name),
    description = COALESCE(?2, description),
    owner_user_id = COALESCE(?3, owner_user_id),
    banner_image = COALESCE(?4, banner_image),
    is_public = COALESCE(?5, is_public)
WHERE
    id = ?6
`

type UpdateClubParams struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
	OwnerUserID *string `json:"owner_user_id"`
	BannerImage *string `json:"banner_image"`
	IsPublic    *bool   `json:"is_public"`
	ID          string  `json:"id"`
}

func (q *Queries) UpdateClub(ctx context.Context, arg UpdateClubParams) error {
	_, err := q.db.ExecContext(ctx, updateClub,
		arg.Name,
		arg.Description,
		arg.OwnerUserID,
		arg.BannerImage,
		arg.IsPublic,
		arg.ID,
	)
	return err
}

const updateClubMembership = `-- name: UpdateClubMembership :exec
UPDATE club_membership
SET
    user_points = COALESCE(?1, user_points),
    user_streak = COALESCE(?2, user_streak),
    is_moderator = COALESCE(?3, is_moderator)
WHERE
    user_id = ?4 AND club_id = ?5
`

type UpdateClubMembershipParams struct {
	UserPoints  *float64 `json:"user_points"`
	UserStreak  *int64   `json:"user_streak"`
	IsModerator *bool    `json:"is_moderator"`
	UserID      string   `json:"user_id"`
	ClubID      string   `json:"club_id"`
}

func (q *Queries) UpdateClubMembership(ctx context.Context, arg UpdateClubMembershipParams) error {
	_, err := q.db.ExecContext(ctx, updateClubMembership,
		arg.UserPoints,
		arg.UserStreak,
		arg.IsModerator,
		arg.UserID,
		arg.ClubID,
	)
	return err
}

const updateClubPost = `-- name: UpdateClubPost :exec
UPDATE club_post
SET
    content = COALESCE(?1, content)
WHERE
    id = ?2
`

type UpdateClubPostParams struct {
	Content *string `json:"content"`
	ID      string  `json:"id"`
}

func (q *Queries) UpdateClubPost(ctx context.Context, arg UpdateClubPostParams) error {
	_, err := q.db.ExecContext(ctx, updateClubPost, arg.Content, arg.ID)
	return err
}

const updateClubPostAttachment = `-- name: UpdateClubPostAttachment :exec
UPDATE club_post_attachment
SET
    url = COALESCE(?1, url)
WHERE
    id = ?2
`

type UpdateClubPostAttachmentParams struct {
	Url *string `json:"url"`
	ID  string  `json:"id"`
}

func (q *Queries) UpdateClubPostAttachment(ctx context.Context, arg UpdateClubPostAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, updateClubPostAttachment, arg.Url, arg.ID)
	return err
}
