// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: club.sql

package repository

import (
	"context"
)

const updateClub = `-- name: UpdateClub :exec
UPDATE club
SET
    name = COALESCE(?1, name),
    description = COALESCE(?2, description),
    owner_user_id = COALESCE(?3, owner_user_id),
    banner_image = COALESCE(?4, banner_image),
    is_public = COALESCE(?5, is_public)
WHERE
    id = ?6
`

type UpdateClubParams struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
	OwnerUserID *string `json:"owner_user_id"`
	BannerImage *string `json:"banner_image"`
	IsPublic    *bool   `json:"is_public"`
	ID          string  `json:"id"`
}

func (q *Queries) UpdateClub(ctx context.Context, arg UpdateClubParams) error {
	_, err := q.db.ExecContext(ctx, updateClub,
		arg.Name,
		arg.Description,
		arg.OwnerUserID,
		arg.BannerImage,
		arg.IsPublic,
		arg.ID,
	)
	return err
}

const updateClubMembership = `-- name: UpdateClubMembership :exec
UPDATE club_membership
SET
    user_points = COALESCE(?1, user_points),
    user_streak = COALESCE(?2, user_streak),
    is_moderator = COALESCE(?3, is_moderator)
WHERE
    user_id = ?4 AND club_id = ?5
`

type UpdateClubMembershipParams struct {
	UserPoints  *float64 `json:"user_points"`
	UserStreak  *int64   `json:"user_streak"`
	IsModerator *bool    `json:"is_moderator"`
	UserID      string   `json:"user_id"`
	ClubID      string   `json:"club_id"`
}

func (q *Queries) UpdateClubMembership(ctx context.Context, arg UpdateClubMembershipParams) error {
	_, err := q.db.ExecContext(ctx, updateClubMembership,
		arg.UserPoints,
		arg.UserStreak,
		arg.IsModerator,
		arg.UserID,
		arg.ClubID,
	)
	return err
}

const updateClubPost = `-- name: UpdateClubPost :exec
UPDATE club_post
SET
    content = COALESCE(?1, content)
WHERE
    id = ?2
`

type UpdateClubPostParams struct {
	Content *string `json:"content"`
	ID      string  `json:"id"`
}

func (q *Queries) UpdateClubPost(ctx context.Context, arg UpdateClubPostParams) error {
	_, err := q.db.ExecContext(ctx, updateClubPost, arg.Content, arg.ID)
	return err
}

const updateClubPostAttachment = `-- name: UpdateClubPostAttachment :exec
UPDATE club_post_attachment
SET
    url = COALESCE(?1, url)
WHERE
    id = ?2
`

type UpdateClubPostAttachmentParams struct {
	Url *string `json:"url"`
	ID  string  `json:"id"`
}

func (q *Queries) UpdateClubPostAttachment(ctx context.Context, arg UpdateClubPostAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, updateClubPostAttachment, arg.Url, arg.ID)
	return err
}
