// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metric.sql

package repository

import (
	"context"
)

const updateMetric = `-- name: UpdateMetric :exec
UPDATE metric
SET
    title = COALESCE(?1, title),
    description = COALESCE(?2, description),
    interval = COALESCE(?3, interval),
    unit = COALESCE(?4, unit),
    requires_verification = COALESCE(?5, requires_verification)
WHERE
    id = ?6
`

type UpdateMetricParams struct {
	Title                *string `json:"title"`
	Description          *string `json:"description"`
	Interval             *string `json:"interval"`
	Unit                 *string `json:"unit"`
	RequiresVerification *bool   `json:"requires_verification"`
	ID                   string  `json:"id"`
}

func (q *Queries) UpdateMetric(ctx context.Context, arg UpdateMetricParams) error {
	_, err := q.db.ExecContext(ctx, updateMetric,
		arg.Title,
		arg.Description,
		arg.Interval,
		arg.Unit,
		arg.RequiresVerification,
		arg.ID,
	)
	return err
}

const updateMetricEntry = `-- name: UpdateMetricEntry :exec
UPDATE metric_entry
SET
    value = COALESCE(?1, value)
WHERE
    user_id = ?2 AND metric_instance_id = ?3
`

type UpdateMetricEntryParams struct {
	Value            *float64 `json:"value"`
	UserID           string   `json:"user_id"`
	MetricInstanceID string   `json:"metric_instance_id"`
}

func (q *Queries) UpdateMetricEntry(ctx context.Context, arg UpdateMetricEntryParams) error {
	_, err := q.db.ExecContext(ctx, updateMetricEntry, arg.Value, arg.UserID, arg.MetricInstanceID)
	return err
}

const updateMetricEntryAttachment = `-- name: UpdateMetricEntryAttachment :exec
UPDATE metric_entry_attachment
SET
    url = COALESCE(?1, url)
WHERE
    id = ?2
`

type UpdateMetricEntryAttachmentParams struct {
	Url *string `json:"url"`
	ID  string  `json:"id"`
}

func (q *Queries) UpdateMetricEntryAttachment(ctx context.Context, arg UpdateMetricEntryAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, updateMetricEntryAttachment, arg.Url, arg.ID)
	return err
}

const updateMetricEntryVerification = `-- name: UpdateMetricEntryVerification :exec
UPDATE metric_entry_verification
SET
    verified = COALESCE(?1, verified),
    reason = COALESCE(?2, reason)
WHERE
    metric_entry_id = ?3 AND verifier_user_id = ?4
`

type UpdateMetricEntryVerificationParams struct {
	Verified       *bool   `json:"verified"`
	Reason         *string `json:"reason"`
	MetricEntryID  string  `json:"metric_entry_id"`
	VerifierUserID string  `json:"verifier_user_id"`
}

func (q *Queries) UpdateMetricEntryVerification(ctx context.Context, arg UpdateMetricEntryVerificationParams) error {
	_, err := q.db.ExecContext(ctx, updateMetricEntryVerification,
		arg.Verified,
		arg.Reason,
		arg.MetricEntryID,
		arg.VerifierUserID,
	)
	return err
}
