// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"
)

type Querier interface {
	CreateFriend(ctx context.Context, arg CreateFriendParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	// assumes user_id < friend_id
	DeleteFriend(ctx context.Context, arg DeleteFriendParams) error
	DeleteUser(ctx context.Context, id string) error
	// assumes user_id < friend_id
	GetFriends(ctx context.Context, id string) ([]GetFriendsRow, error)
	GetUserDisplay(ctx context.Context, id string) (GetUserDisplayRow, error)
	GetUserLogin(ctx context.Context, username string) (GetUserLoginRow, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfilePicture(ctx context.Context, arg UpdateUserProfilePictureParams) error
}

var _ Querier = (*Queries)(nil)
