// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package repository

import (
	"context"
	"time"
)

const createFriend = `-- name: CreateFriend :exec
INSERT INTO user_friendship (user_id, friend_id)
VALUES (?, ?)
`

type CreateFriendParams struct {
	UserID   string `json:"user_id"`
	FriendID string `json:"friend_id"`
}

func (q *Queries) CreateFriend(ctx context.Context, arg CreateFriendParams) error {
	_, err := q.db.ExecContext(ctx, createFriend, arg.UserID, arg.FriendID)
	return err
}

const createItem = `-- name: CreateItem :exec
INSERT INTO items (id, name, description, is_available, owner_id)
VALUES (?, ?, ?, ?, ?)
`

type CreateItemParams struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	IsAvailable bool    `json:"is_available"`
	OwnerID     string  `json:"owner_id"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) error {
	_, err := q.db.ExecContext(ctx, createItem,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsAvailable,
		arg.OwnerID,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO user (id, email, username, password)
VALUES (?, ?, ?, ?)
`

type CreateUserParams struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.Password,
	)
	return err
}

const deleteFriend = `-- name: DeleteFriend :exec
DELETE FROM user_friendship
WHERE user_id = ? AND friend_id = ?
`

type DeleteFriendParams struct {
	UserID   string `json:"user_id"`
	FriendID string `json:"friend_id"`
}

// assumes user_id < friend_id
func (q *Queries) DeleteFriend(ctx context.Context, arg DeleteFriendParams) error {
	_, err := q.db.ExecContext(ctx, deleteFriend, arg.UserID, arg.FriendID)
	return err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM items WHERE id = ?
`

func (q *Queries) DeleteItem(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteItem, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM user WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getFriends = `-- name: GetFriends :many
SELECT u.username, u.profile_picture, u.id  FROM user u WHERE u.id IN (
    SELECT friend_id FROM user_friendship f WHERE f.user_id = ?1
    UNION
    SELECT user_id FROM user_friendship f WHERE f.friend_id = ?1
)
`

type GetFriendsRow struct {
	Username       string  `json:"username"`
	ProfilePicture *string `json:"profile_picture"`
	ID             string  `json:"id"`
}

// assumes user_id < friend_id
// TODO: add user friendship created at
func (q *Queries) GetFriends(ctx context.Context, id string) ([]GetFriendsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFriends, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFriendsRow
	for rows.Next() {
		var i GetFriendsRow
		if err := rows.Scan(&i.Username, &i.ProfilePicture, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItem = `-- name: GetItem :one
SELECT id, name, description, is_available, owner_id, created_at, updated_at
FROM items
WHERE id = ?
`

func (q *Queries) GetItem(ctx context.Context, id string) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsAvailable,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemsByOwner = `-- name: GetItemsByOwner :many
SELECT id, name, description, is_available, owner_id, created_at, updated_at
FROM items
WHERE owner_id = ?
`

func (q *Queries) GetItemsByOwner(ctx context.Context, ownerID string) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, getItemsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsAvailable,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTradeByID = `-- name: GetTradeByID :one
SELECT id, proposer_id, proposer_item_id, responder_id, responder_item_id, status, created_at, updated_at
FROM trades
WHERE id = ?
`

func (q *Queries) GetTradeByID(ctx context.Context, id string) (Trade, error) {
	row := q.db.QueryRowContext(ctx, getTradeByID, id)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.ProposerID,
		&i.ProposerItemID,
		&i.ResponderID,
		&i.ResponderItemID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserClubs = `-- name: GetUserClubs :many
SELECT
    c.id AS club_id, c.name,
    c.description, c.created_at,
    c.banner_image, cm.user_points,
    cm.user_streak, cm.created_at AS joined_at
FROM club c
JOIN club_membership cm ON c.id = cm.club_id
WHERE cm.user_id = ?1
ORDER BY cm.created_at DESC
`

type GetUserClubsRow struct {
	ClubID      string    `json:"club_id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	BannerImage *string   `json:"banner_image"`
	UserPoints  float64   `json:"user_points"`
	UserStreak  int64     `json:"user_streak"`
	JoinedAt    time.Time `json:"joined_at"`
}

func (q *Queries) GetUserClubs(ctx context.Context, userID string) ([]GetUserClubsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserClubs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserClubsRow
	for rows.Next() {
		var i GetUserClubsRow
		if err := rows.Scan(
			&i.ClubID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.BannerImage,
			&i.UserPoints,
			&i.UserStreak,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserDisplay = `-- name: GetUserDisplay :one
SELECT username, profile_picture, created_at
FROM user
WHERE id = ?
`

type GetUserDisplayRow struct {
	Username       string    `json:"username"`
	ProfilePicture *string   `json:"profile_picture"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) GetUserDisplay(ctx context.Context, id string) (GetUserDisplayRow, error) {
	row := q.db.QueryRowContext(ctx, getUserDisplay, id)
	var i GetUserDisplayRow
	err := row.Scan(&i.Username, &i.ProfilePicture, &i.CreatedAt)
	return i, err
}

const getUserLoginByEmail = `-- name: GetUserLoginByEmail :one
SELECT id, email, username, password
FROM user
WHERE email = ?
`

type GetUserLoginByEmailRow struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) GetUserLoginByEmail(ctx context.Context, email string) (GetUserLoginByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserLoginByEmail, email)
	var i GetUserLoginByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
	)
	return i, err
}

const getUserLoginByUsername = `-- name: GetUserLoginByUsername :one
SELECT id, email, username, password
FROM user
WHERE username = ?
`

type GetUserLoginByUsernameRow struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) GetUserLoginByUsername(ctx context.Context, username string) (GetUserLoginByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserLoginByUsername, username)
	var i GetUserLoginByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
	)
	return i, err
}

const getUserMetricEntries = `-- name: GetUserMetricEntries :many
SELECT me.user_id, me.metric_instance_id, me.value, me.created_at, me.updated_at FROM metric_entry me
JOIN metric m ON me.metric_id = m.id
JOIN club_membership cm ON m.club_id = cm.club_id
WHERE cm.user_id = ?
`

func (q *Queries) GetUserMetricEntries(ctx context.Context, userID string) ([]MetricEntry, error) {
	rows, err := q.db.QueryContext(ctx, getUserMetricEntries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetricEntry
	for rows.Next() {
		var i MetricEntry
		if err := rows.Scan(
			&i.UserID,
			&i.MetricInstanceID,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserMetrics = `-- name: GetUserMetrics :many
SELECT m.id, m.club_id, m.title, m.description, m.interval, m.start_at, m.unit, m.unit_is_integer, m.requires_verification, m.created_at, m.updated_at FROM metric m
JOIN club_membership cm ON m.club_id = cm.club_id
WHERE cm.user_id = ?
`

func (q *Queries) GetUserMetrics(ctx context.Context, userID string) ([]Metric, error) {
	rows, err := q.db.QueryContext(ctx, getUserMetrics, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Metric
	for rows.Next() {
		var i Metric
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.Title,
			&i.Description,
			&i.Interval,
			&i.StartAt,
			&i.Unit,
			&i.UnitIsInteger,
			&i.RequiresVerification,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tradeCreate = `-- name: TradeCreate :exec
INSERT INTO trades (id, proposer_id, proposer_item_id, responder_id, responder_item_id, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type TradeCreateParams struct {
	ID              string    `json:"id"`
	ProposerID      string    `json:"proposer_id"`
	ProposerItemID  string    `json:"proposer_item_id"`
	ResponderID     string    `json:"responder_id"`
	ResponderItemID string    `json:"responder_item_id"`
	Status          string    `json:"status"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) TradeCreate(ctx context.Context, arg TradeCreateParams) error {
	_, err := q.db.ExecContext(ctx, tradeCreate,
		arg.ID,
		arg.ProposerID,
		arg.ProposerItemID,
		arg.ResponderID,
		arg.ResponderItemID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const transferItemOwnership = `-- name: TransferItemOwnership :exec
UPDATE items
SET owner_id = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type TransferItemOwnershipParams struct {
	OwnerID string `json:"owner_id"`
	ID      string `json:"id"`
}

func (q *Queries) TransferItemOwnership(ctx context.Context, arg TransferItemOwnershipParams) error {
	_, err := q.db.ExecContext(ctx, transferItemOwnership, arg.OwnerID, arg.ID)
	return err
}

const updateItem = `-- name: UpdateItem :exec
UPDATE items
SET
    name = COALESCE(?1, name),
    description = COALESCE(?2, description),
    is_available = COALESCE(?3, is_available),
    owner_id = COALESCE(?4, owner_id)
WHERE
    id = ?5
`

type UpdateItemParams struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
	IsAvailable *bool   `json:"is_available"`
	OwnerID     *string `json:"owner_id"`
	ID          string  `json:"id"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) error {
	_, err := q.db.ExecContext(ctx, updateItem,
		arg.Name,
		arg.Description,
		arg.IsAvailable,
		arg.OwnerID,
		arg.ID,
	)
	return err
}

const updateTradeStatus = `-- name: UpdateTradeStatus :exec
UPDATE trades
SET status = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateTradeStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateTradeStatus(ctx context.Context, arg UpdateTradeStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTradeStatus, arg.Status, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE user
SET
    email = COALESCE(?1, email),
    username = COALESCE(?2, username),
    password = COALESCE(?3, password),
    profile_picture = COALESCE(?4, profile_picture)
WHERE
    id = ?5
`

type UpdateUserParams struct {
	Email          *string `json:"email"`
	Username       *string `json:"username"`
	Password       *string `json:"password"`
	ProfilePicture *string `json:"profile_picture"`
	ID             string  `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.ProfilePicture,
		arg.ID,
	)
	return err
}

const updateUserPrivateMessage = `-- name: UpdateUserPrivateMessage :exec
UPDATE user_private_message
SET
    content = COALESCE(?1, content)
WHERE
    id = ?2
`

type UpdateUserPrivateMessageParams struct {
	Content *string `json:"content"`
	ID      string  `json:"id"`
}

func (q *Queries) UpdateUserPrivateMessage(ctx context.Context, arg UpdateUserPrivateMessageParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPrivateMessage, arg.Content, arg.ID)
	return err
}
